In [1]:
import numpy as np

In [30]:
#creating an array:
def make_ary():
    a = [2,3,4]
    b = [5,6,7]
    print(np.array([a,b]))

In [60]:
def initial_values():
    print(np.empty(5))
    print(np.empty([5,4]))
    print(np.empty([5,4,3]))
    #the empty array contains whatever is in the computers memory
    print(np.ones([5,4]))
    #np.ones defaults np.float32 but we can make it output np.int8 with dtype=np.int8
    print(np.ones([2,2], dtype=np.int8))


In [61]:
if __name__ == "__main__":
    #make_ary()
    initial_values()

[ -1.49166815e-154  -1.49166815e-154   2.27751254e-314   0.00000000e+000
  -1.49166815e-154]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[[ -1.49166815e-154  -1.49166815e-154   2.21657512e-314]
  [  2.47032823e-323   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   2.23401485e-314   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]

 [[  0.00000000e+000  -2.00009736e-266   2.23348987e-314]
  [  2.27802358e-314   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]

 [[  0.00000000e+000   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   2.27761318e-314   0.00000000e+000]
  [  0.00000000e+000   2.51078366e-261   2.22578919e-314]
  [  2.23488267e-314   7.11454530e-322   0.00000000e+000]]

 [[  0.00000000e+000   5.74788206e-230   2.23379972e-314]
  [  2.22006026e-314  -1.15042435e+264   2.22428533