In [56]:
import numpy as np

In [57]:
one = np.ones([5,5], dtype=int)
zero = np.zeros([5,5])
rand = np.random.randint(0,high=100,size=(5,5))
ary = np.array([one,zero,rand])
print(ary)

[[[  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[ 99.  73.  89.  10.  58.]
  [ 53.  24.  50.  12.  58.]
  [ 33.  78.  48.  25.  54.]
  [ 82.  64.   7.  10.  32.]
  [ 57.  55.  46.  56.  99.]]]


In [58]:
type(ary[0,0,0])
print(ary[])

[[[  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[ 99.  73.  89.  10.  58.]
  [ 53.  24.  50.  12.  58.]
  [ 33.  78.  48.  25.  54.]
  [ 82.  64.   7.  10.  32.]
  [ 57.  55.  46.  56.  99.]]]
