In [187]:
import numpy as np
import matplotlib.pyplot as plt

In [188]:
#3
np.random.seed(101)
one = np.ones([5,5])
zero = np.zeros([5,5])
rand = np.random.randint(0,high=100,size=(5,5))
ary = np.array([one,zero,rand])
print(ary)

[[[  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[ 95.  11.  81.  70.  63.]
  [ 87.  75.   9.  77.  40.]
  [  4.  63.  40.  60.  92.]
  [ 64.   5.  12.  93.  40.]
  [ 49.  83.   8.  29.  59.]]]


In [189]:
#4
print(ary[0])
print(ary[0:3,-2:,-2:])
ary[0, 0:5:2, 0:5:2] = 0
ary[0, 1:5:2, 1:5:2] = 0
print(ary)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[[  1.   1.]
  [  1.   1.]]

 [[  0.   0.]
  [  0.   0.]]

 [[ 93.  40.]
  [ 29.  59.]]]
[[[  0.   1.   0.   1.   0.]
  [  1.   0.   1.   0.   1.]
  [  0.   1.   0.   1.   0.]
  [  1.   0.   1.   0.   1.]
  [  0.   1.   0.   1.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[ 95.  11.  81.  70.  63.]
  [ 87.  75.   9.  77.  40.]
  [  4.  63.  40.  60.  92.]
  [ 64.   5.  12.  93.  40.]
  [ 49.  83.   8.  29.  59.]]]


In [190]:
#5
print(rand)
print(rand.sum())
print(rand.max())
print(rand.mean(axis=1))
mean = rand.mean()
print(rand[rand<mean])
rand[rand<mean]=mean
print(rand)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]
 [64  5 12 93 40]
 [49 83  8 29 59]]
1309
95
[ 64.   57.6  51.8  42.8  45.6]
[11  9 40  4 40  5 12 40 49  8 29]
[[95 52 81 70 63]
 [87 75 52 77 52]
 [52 63 52 60 92]
 [64 52 52 93 52]
 [52 83 52 52 59]]


In [232]:
#6
a=np.array([10,20,30,40])
b=np.array([5,10,15,20])

print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a.dot(b))

[15 30 45 60]
[ 5 10 15 20]
[ 2.  2.  2.  2.]
[ 50 200 450 800]
1500


In [299]:
#bonus
aapl = np.genfromtxt('data/AAPL.csv', delimiter=',')
spy = np.genfromtxt('data/SPY.csv', delimiter=',')
cost = np.genfromtxt('data/COST.csv', delimiter=',')

In [303]:
prices = np.array([(aapl[1:,6])[::-1], (spy[1:,6])[::-1], (cost[1:,6])[::-1]])
div = prices[0:, 0]
norm = prices / div[:,None]
print(norm)

[[  1.           0.98557692   1.03044872 ...,  26.55208333  26.46594551
   26.83453526]
 [  1.           1.00079302   1.01594854 ...,   1.2645167    1.26804124
    1.27227068]
 [  1.           1.03983051   1.04449153 ...,   2.12817797   2.10847458
    2.1375    ]]


In [310]:
allocs = np.array([.2,.6,.1])
alloced = norm * allocs[:,None]
print(alloced)

[[ 0.2         0.19711538  0.20608974 ...,  5.31041667  5.2931891
   5.36690705]
 [ 0.6         0.60047581  0.60956913 ...,  0.75871002  0.76082474
   0.76336241]
 [ 0.1         0.10398305  0.10444915 ...,  0.2128178   0.21084746  0.21375   ]]


In [311]:
start_val = np.array([200,600,100])
pos_vals = alloced*start_val[:,None]
print(pos_vals)

[[   40.            39.42307692    41.21794872 ...,  1062.08333333
   1058.63782051  1073.38141026]
 [  360.           360.28548771   365.74147502 ...,   455.2260111
    456.49484536   458.01744647]
 [   10.            10.39830508    10.44491525 ...,    21.28177966
     21.08474576    21.375     ]]


In [307]:
port_val = pos_vals.sum(axis=0)
print(port_val)

[  410.           410.10686972   417.40433899 ...,  1538.5911241
  1536.21741164  1552.77385673]


In [309]:
np.shape(port_val)

(3175,)